// <auto-generated />
using System;
using GestaoEncomendas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoEncomendas.Migrations
{
    [DbContext(typeof(EncomendasDbContext))]
    [Migration("20261006163357_InserirCidades")]
    partial class InserirCidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoEncomendas.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique();

                    b.HasIndex("EstadoId");

                    b.ToTable("cidade", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("Numero", "TipoDocumentoId")
                        .IsUnique();

                    b.HasIndex("TipoDocumentoId", "PessoaId")
                        .IsUnique();

                    b.ToTable("documento", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Encomenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinatario_id");

                    b.Property<Guid>("EncomendaStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<Guid>("EnderecoEntregaId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_entrega_id");

                    b.Property<DateTime>("Inclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inclusao");

                    b.Property<Guid>("RemetenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("remetente_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("EncomendaStatusId");

                    b.HasIndex("EnderecoEntregaId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("encomenda", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.EncomendaStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("encomenda_status", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("cep");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Uf")
                        .IsUnique();

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnderecoPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_principal_id");

                    b.Property<string>("Fone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TipoPessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_pessoa_id");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoPrincipalId");

                    b.HasIndex("TipoPessoaId");

                    b.ToTable("pessoa", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.TipoPessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("tipo_pessoa", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Altura")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("altura");

                    b.Property<decimal>("Comprimento")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("comprimento");

                    b.Property<Guid>("EncomendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("encomenda_id");

                    b.Property<decimal>("Largura")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("largura");

                    b.Property<decimal>("PesoBruto")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("peso_bruto");

                    b.HasKey("Id");

                    b.HasIndex("EncomendaId");

                    b.ToTable("volume", (string)null);
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Cidade", b =>
                {
                    b.HasOne("GestaoEncomendas.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Documento", b =>
                {
                    b.HasOne("GestaoEncomendas.Entities.Pessoa", "Pessoa")
                        .WithMany("Documentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEncomendas.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Encomenda", b =>
                {
                    b.HasOne("GestaoEncomendas.Entities.Pessoa", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEncomendas.Entities.EncomendaStatus", "EncomendaStatus")
                        .WithMany()
                        .HasForeignKey("EncomendaStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEncomendas.Entities.Endereco", "EnderecoEntrega")
                        .WithMany()
                        .HasForeignKey("EnderecoEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEncomendas.Entities.Pessoa", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("EncomendaStatus");

                    b.Navigation("EnderecoEntrega");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Endereco", b =>
                {
                    b.HasOne("GestaoEncomendas.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Pessoa", b =>
                {
                    b.HasOne("GestaoEncomendas.Entities.Endereco", "EnderecoPrincipal")
                        .WithMany()
                        .HasForeignKey("EnderecoPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEncomendas.Entities.TipoPessoa", "TipoPessoa")
                        .WithMany()
                        .HasForeignKey("TipoPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnderecoPrincipal");

                    b.Navigation("TipoPessoa");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Volume", b =>
                {
                    b.HasOne("GestaoEncomendas.Entities.Encomenda", "Encomenda")
                        .WithMany("Volumes")
                        .HasForeignKey("EncomendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encomenda");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Encomenda", b =>
                {
                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("GestaoEncomendas.Entities.Pessoa", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
